[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"

# Optional: Redirect all routes to index.html (useful for SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
