[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301